FROM apache/superset:latest
USER root
RUN pip install sqlalchemy-trino pillow
ENV PYTHONPATH="${PYTHONPATH}:/app/pythonpath:/app/.venv/lib/python3.10/site-packages:/usr/local/lib/python3.10/site-packages"
USER superset